name: Tests & Quality

on:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: true
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180
          record: false
          command: npx cypress run
