name: Tests & Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress without visual tests
        uses: cypress-io/github-action@v4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: true
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180
          record: false
          command: npx run cypress
