name: "Report deployed info metrics"
description: "Few metrics to set alerts on to check all is deployed fine"
inputs:
  environment:
    description: "Environment pretty name"
    required: true
  clone-dir:
    description: "Name of the parent where the action is cloned"
    required: false
    default: "login-e2e-tests"

runs:
  using: "composite"
  steps:
    - run: ${{ inputs.clone-dir }}/deploy/.github/run-tests.sh
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
